# Generated by Django 4.1.2 on 2022-11-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_alter_employeedetails_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_image'),
        ),
    ]
