# Generated by Django 4.1.2 on 2022-11-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_employeedetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='image',
            field=models.ImageField(blank=True, default='static/employee_image/profile_image.jpg', null=True, upload_to='employee_image'),
        ),
    ]
