# Generated by Django 4.1.2 on 2022-11-13 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
    ]
